# Generated by Django 6.0.3 on 2026-07-04 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Corrdinator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('utr', models.CharField(blank=True, max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='Corrdinator.coordinatorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('student_class', models.PositiveSmallIntegerField()),
                ('category', models.CharField(max_length=1)),
                ('subjects', models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('both', 'Math & Science')], max_length=20)),
                ('fee', models.PositiveIntegerField(default=70)),
                ('parent_name', models.CharField(blank=True, max_length=255)),
                ('parent_contact', models.CharField(blank=True, max_length=10)),
                ('roll_number', models.CharField(blank=True, max_length=30)),
                ('admit_card_released', models.BooleanField(default=False)),
                ('math_marks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('science_marks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Corrdinator.coordinatorprofile')),
            ],
        ),
    ]
