# Generated by Django 6.0.3 on 2026-07-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registartion', '0002_add_results_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cs_marks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='english_marks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='fee',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.CharField(help_text='Comma-separated subject codes (english,math,science,cs)', max_length=50),
        ),
    ]
