# Generated by Django 6.0.6 on 2026-07-05 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registartion', '0003_student_cs_marks_student_english_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationsettings',
            name='admit_card_release_date',
            field=models.DateField(default=datetime.date(2026, 7, 29)),
        ),
        migrations.AddField(
            model_name='registrationsettings',
            name='announcement_message',
            field=models.CharField(blank=True, default='Registration is now open for Brain-O-Math Olympiad 2026.', max_length=255),
        ),
        migrations.AddField(
            model_name='registrationsettings',
            name='award_ceremony_date',
            field=models.DateField(default=datetime.date(2026, 10, 6)),
        ),
        migrations.AddField(
            model_name='registrationsettings',
            name='award_description',
            field=models.CharField(default='Silver Medal for the highest scorer in any one subject.', max_length=255),
        ),
        migrations.AddField(
            model_name='registrationsettings',
            name='computer_science_exam_date',
            field=models.DateField(default=datetime.date(2026, 8, 7)),
        ),
        migrations.AddField(
            model_name='registrationsettings',
            name='computer_science_exam_time',
            field=models.CharField(default='2:30 PM – 3:30 PM', max_length=50),
        ),
        migrations.AddField(
            model_name='registrationsettings',
            name='contact_whatsapp_url',
            field=models.URLField(default='https://wa.me/917384687034?text=Hi%20I%27d%20like%20to%20know%20more%20about%20Brain-O-Math.'),
        ),
        migrations.AddField(
            model_name='registrationsettings',
            name='english_exam_date',
            field=models.DateField(default=datetime.date(2026, 8, 7)),
        ),
        migrations.AddField(
            model_name='registrationsettings',
            name='english_exam_time',
            field=models.CharField(default='1:00 PM – 2:00 PM', max_length=50),
        ),
        migrations.AddField(
            model_name='registrationsettings',
            name='event_year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='registrationsettings',
            name='handbook_url',
            field=models.URLField(default='https://drive.google.com/file/d/13rx7WxS8U0DYaQ0w4gv7dxd0k1II4kw6/view?usp=drivesdk'),
        ),
        migrations.AddField(
            model_name='registrationsettings',
            name='last_date_to_apply',
            field=models.DateField(default=datetime.date(2026, 7, 27)),
        ),
        migrations.AddField(
            model_name='registrationsettings',
            name='mathematics_exam_date',
            field=models.DateField(default=datetime.date(2026, 8, 8)),
        ),
        migrations.AddField(
            model_name='registrationsettings',
            name='mathematics_exam_time',
            field=models.CharField(default='9:30 AM – 10:30 AM', max_length=50),
        ),
        migrations.AddField(
            model_name='registrationsettings',
            name='organizer_link',
            field=models.URLField(default='https://www.doonheritageschool.co.in'),
        ),
        migrations.AddField(
            model_name='registrationsettings',
            name='organizer_name',
            field=models.CharField(default='Doon Heritage School, Siliguri', max_length=255),
        ),
        migrations.AddField(
            model_name='registrationsettings',
            name='registration_fee_per_subject',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='registrationsettings',
            name='result_declaration_date',
            field=models.DateField(default=datetime.date(2026, 10, 1)),
        ),
        migrations.AddField(
            model_name='registrationsettings',
            name='science_exam_date',
            field=models.DateField(default=datetime.date(2026, 8, 8)),
        ),
        migrations.AddField(
            model_name='registrationsettings',
            name='science_exam_time',
            field=models.CharField(default='11:00 AM – 12:00 PM', max_length=50),
        ),
    ]
