# Generated by Django 6.0.3 on 2026-07-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registartion', '0004_registrationsettings_admit_card_release_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.CharField(blank=True, help_text='Comma-separated subject codes (english,math,science,cs)', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='selected_subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='Registartion.subject'),
        ),
    ]
