# Generated by Django 6.0.3 on 2026-07-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registartion', '0005_subject_alter_student_subjects_and_more'),
    ]

    operations = [
    ]
