# Generated by Django 6.0.6 on 2026-07-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registartion', '0006_populate_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='selected_subjects',
        ),
        migrations.AlterField(
            model_name='registrationsettings',
            name='handbook_url',
            field=models.URLField(default='https://drive.google.com/file/d/1rfNxAcdV03DBSFH_xu6YW2myWc9twhRL/view?usp=drivesdk'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.CharField(help_text='Comma-separated subject codes (english,math,science,cs)', max_length=50),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
