# Generated by Django 6.0.3 on 2026-07-27 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registartion', '0007_remove_student_selected_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpayment',
            name='venue',
            field=models.CharField(choices=[('Doon Heritage School, Siliguri', 'Doon Heritage School, Siliguri'), ('Don Bosco School, Mayanaguri', 'Don Bosco School, Mayanaguri')], default='Doon Heritage School, Siliguri', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='venue',
            field=models.CharField(choices=[('Doon Heritage School, Siliguri', 'Doon Heritage School, Siliguri'), ('Don Bosco School, Mayanaguri', 'Don Bosco School, Mayanaguri')], default='Doon Heritage School, Siliguri', max_length=255),
        ),
        migrations.AlterField(
            model_name='registrationsettings',
            name='admit_card_release_date',
            field=models.DateField(default=datetime.date(2026, 8, 4)),
        ),
        migrations.AlterField(
            model_name='registrationsettings',
            name='computer_science_exam_date',
            field=models.DateField(default=datetime.date(2026, 8, 8)),
        ),
        migrations.AlterField(
            model_name='registrationsettings',
            name='english_exam_date',
            field=models.DateField(default=datetime.date(2026, 8, 8)),
        ),
        migrations.AlterField(
            model_name='registrationsettings',
            name='handbook_url',
            field=models.URLField(default='https://drive.google.com/file/d/15I5Cd6Hp384KRoHtcxUBXFJIl7fVvr51/view?usp=drive_link'),
        ),
        migrations.AlterField(
            model_name='registrationsettings',
            name='last_date_to_apply',
            field=models.DateField(default=datetime.date(2026, 8, 2)),
        ),
    ]
