# Generated by Django 6.0.6 on 2026-08-01 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registartion', '0008_registrationpayment_venue_student_venue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationsettings',
            name='admit_card_release_date',
            field=models.DateField(default=datetime.date(2026, 8, 5)),
        ),
        migrations.AlterField(
            model_name='registrationsettings',
            name='last_date_to_apply',
            field=models.DateField(default=datetime.date(2026, 8, 4)),
        ),
    ]
