# Generated by Django 6.0.3 on 2026-09-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registartion', '0012_remove_legacy_bom_roll_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationpayment',
            name='venue',
            field=models.CharField(choices=[('Doon Heritage School, Siliguri', 'Doon Heritage School, Siliguri'), ('Don Bosco School, Mayanaguri', 'Don Bosco School, Mayanaguri'), ('Delhi World Public School, Malda', 'Delhi World Public School, Malda')], default='Doon Heritage School, Siliguri', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='venue',
            field=models.CharField(choices=[('Doon Heritage School, Siliguri', 'Doon Heritage School, Siliguri'), ('Don Bosco School, Mayanaguri', 'Don Bosco School, Mayanaguri'), ('Delhi World Public School, Malda', 'Delhi World Public School, Malda')], default='Doon Heritage School, Siliguri', max_length=255),
        ),
    ]
