# Generated by Django 6.0.6 on 2026-07-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corrdinator', '0002_activate_existing_coordinators'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatorprofile',
            name='force_password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
